apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort   # Change to LoadBalancer if using cloud
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007   # Accessible port on node
